apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
  - image: ravenwijaya/client
    context: client
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
        - src: 'src/**/*.js'
          dest: .
  - image: ravenwijaya/comments
    context: comments
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
        - src: '*.js'
          dest: .
  - image: ravenwijaya/event-bus
    context: event-bus
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
        - src: '*.js'
          dest: .
  - image: ravenwijaya/moderation
    context: moderation
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
        - src: '*.js'
          dest: .
  - image: ravenwijaya/posts
    context: posts
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
        - src: '*.js'
          dest: .
  - image: ravenwijaya/query
    context: query
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
        - src: '*.js'
          dest: .
      
